# ・先にプッシュ動きを確認する。
# ・プルリクエストは後で確認する。

name: Test01

# プッシュされたら実行する。
# masterブランチのプッシュは除外
#on:
#  [pull_request]
#  [push]
#  push:
#    branches-ignore:
#      - 'master'
#  pull_request:
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  job01:
    runs-on: macos-latest
    steps:
      - name: テスト01 開始
        run: echo "開始します。"

      - uses: actions/checkout@v2

      - name: テスト01 build
        run: swift build
        
      - name: テスト01 test
        run: swift test
      
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: テスト01 終了
        run: echo "終了します。"
