# ・先にプッシュ動きを確認する。
# ・プルリクエストは後で確認する。

name: Test01

# プッシュされたら実行する。
# masterブランチのプッシュは除外
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  job01:
    runs-on: macos-latest
    steps:
      - name: テスト01 開始
        run: echo "開始します。"
      - name: テスト01 build
        run: swift build
      - name: テスト01 終了
        run: echo "終了します。"
